import type { SalesResourceConfig } from './types';

export const salesResourceConfigs: Record<string, SalesResourceConfig> = {
  customers: {
    key: 'customers',
    title: '客户管理',
    createLabel: '新增客户',
    searchPlaceholder: '搜索客户名称、联系人、手机号、负责人',
    rowKey: 'id',
    primaryKey: 'name',
    statusKey: 'statusName',
    columns: [
      { key: 'code', title: '客户编码', width: 140 },
      { key: 'name', title: '客户名称', width: 220, link: true },
      { key: 'groupName', title: '客户分组', width: 120 },
      { key: 'contactName', title: '联系人', width: 110 },
      { key: 'contactPhone', title: '联系电话', width: 140 },
      { key: 'managerName', title: '负责人', width: 110 },
      { key: 'creditLimit', title: '信用额度', width: 120, numeric: true },
      { key: 'receivableAmount', title: '应收金额', width: 120, numeric: true },
      { key: 'creditStatusName', title: '信用状态', width: 110, status: true },
      { key: 'statusName', title: '状态', width: 90, status: true },
    ],
    formFields: [
      { key: 'name', label: '客户名称', required: true },
      { key: 'groupName', label: '客户分组', type: 'select', options: ['重点客户', '普通客户', '渠道客户'] },
      { key: 'contactName', label: '联系人' },
      { key: 'contactPhone', label: '联系电话' },
      { key: 'managerName', label: '负责人' },
      { key: 'creditLimit', label: '信用额度', type: 'number' },
    ],
  },
  'sales-plans': {
    key: 'sales-plans',
    title: '销售计划',
    createLabel: '新增计划',
    searchPlaceholder: '搜索计划名称、编号、产品、负责人',
    rowKey: 'id',
    primaryKey: 'name',
    statusKey: 'statusName',
    columns: [
      { key: 'code', title: '计划编号', width: 150 },
      { key: 'name', title: '计划名称', width: 200, link: true },
      { key: 'productSummary', title: '产品摘要', width: 180 },
      { key: 'cycle', title: '计划周期', width: 190 },
      { key: 'ownerName', title: '负责人', width: 110 },
      { key: 'targetAmount', title: '目标金额', width: 120, numeric: true },
      { key: 'doneAmount', title: '完成金额', width: 120, numeric: true },
      { key: 'achievementRate', title: '达成率', width: 90, numeric: true },
      { key: 'statusName', title: '状态', width: 110, status: true },
    ],
    formFields: [
      { key: 'name', label: '计划名称', required: true },
      { key: 'productSummary', label: '产品摘要' },
      { key: 'cycleStart', label: '开始日期', type: 'date' },
      { key: 'cycleEnd', label: '结束日期', type: 'date' },
      { key: 'ownerName', label: '负责人' },
      { key: 'targetAmount', label: '目标金额', type: 'number' },
    ],
  },
  'sales-quotes': {
    key: 'sales-quotes',
    title: '报价管理',
    createLabel: '新增报价',
    searchPlaceholder: '搜索报价主题、编号、客户、版本',
    rowKey: 'id',
    primaryKey: 'topic',
    statusKey: 'statusName',
    columns: [
      { key: 'code', title: '报价编号', width: 150 },
      { key: 'topic', title: '报价主题', width: 220, link: true },
      { key: 'quoteTypeName', title: '报价类型', width: 110 },
      { key: 'customerName', title: '客户', width: 180 },
      { key: 'amount', title: '报价金额', width: 120, numeric: true },
      { key: 'priceVersion', title: '价格版本', width: 120 },
      { key: 'conversionStatusName', title: '转化状态', width: 120, status: true },
      { key: 'quoteDate', title: '报价日期', width: 120 },
      { key: 'expireDate', title: '有效期至', width: 120 },
      { key: 'statusName', title: '状态', width: 110, status: true },
    ],
    formFields: [
      { key: 'topic', label: '报价主题', required: true },
      { key: 'customerName', label: '客户' },
      { key: 'quoteTypeName', label: '报价类型', type: 'select', options: ['标准报价', '项目报价', '渠道报价'] },
      { key: 'amount', label: '报价金额', type: 'number' },
      { key: 'quoteDate', label: '报价日期', type: 'date' },
      { key: 'expireDate', label: '有效期至', type: 'date' },
    ],
  },
  'sales-contracts': {
    key: 'sales-contracts',
    title: '合同管理',
    createLabel: '新增合同',
    searchPlaceholder: '搜索合同主题、编号、客户、来源单据',
    rowKey: 'id',
    primaryKey: 'topic',
    statusKey: 'executionStatusName',
    columns: [
      { key: 'code', title: '合同编号', width: 150 },
      { key: 'topic', title: '合同主题', width: 220, link: true },
      { key: 'customerName', title: '客户', width: 180 },
      { key: 'sourceCode', title: '来源单据', width: 150 },
      { key: 'amount', title: '合同金额', width: 120, numeric: true },
      { key: 'orderedAmount', title: '已下单金额', width: 120, numeric: true },
      { key: 'shippedAmount', title: '已发货金额', width: 120, numeric: true },
      { key: 'receivedAmount', title: '已回款金额', width: 120, numeric: true },
      { key: 'expireDate', title: '失效日期', width: 120 },
      { key: 'executionStatusName', title: '履约状态', width: 120, status: true },
    ],
    formFields: [
      { key: 'topic', label: '合同主题', required: true },
      { key: 'customerName', label: '客户' },
      { key: 'sourceCode', label: '来源单据' },
      { key: 'amount', label: '合同金额', type: 'number' },
      { key: 'signedDate', label: '签订日期', type: 'date' },
      { key: 'expireDate', label: '失效日期', type: 'date' },
    ],
  },
  'sales-orders': {
    key: 'sales-orders',
    title: '订单管理',
    createLabel: '新增订单',
    searchPlaceholder: '搜索订单主题、编号、客户、来源单据',
    rowKey: 'id',
    primaryKey: 'topic',
    statusKey: 'statusName',
    columns: [
      { key: 'code', title: '订单编号', width: 150 },
      { key: 'topic', title: '订单主题', width: 220, link: true },
      { key: 'sourceType', title: '来源类型', width: 110 },
      { key: 'sourceCode', title: '来源单据', width: 150 },
      { key: 'customerName', title: '客户', width: 180 },
      { key: 'amount', title: '订单金额', width: 120, numeric: true },
      { key: 'creditCheckName', title: '信用校验', width: 110, status: true },
      { key: 'receivableAmount', title: '应收金额', width: 120, numeric: true },
      { key: 'deliveryDate', title: '交付日期', width: 120 },
      { key: 'progressName', title: '进度', width: 110, status: true },
      { key: 'statusName', title: '状态', width: 110, status: true },
    ],
    formFields: [
      { key: 'topic', label: '订单主题', required: true },
      { key: 'customerName', label: '客户' },
      { key: 'sourceType', label: '来源类型', type: 'select', options: ['合同转订单', '报价转订单', '手动创建'] },
      { key: 'sourceCode', label: '来源单据' },
      { key: 'amount', label: '订单金额', type: 'number' },
      { key: 'deliveryDate', label: '交付日期', type: 'date' },
    ],
  },
};
