export const salesWorkbench = {
  kpis: [
    { tone: 'rose', label: '待审核客户', value: 4, icon: '◇' },
    { tone: 'sand', label: '临近额度客户', value: 6, icon: '!' },
    { tone: 'mint', label: '待执行计划', value: 12, icon: '▤' },
    { tone: 'peach', label: '待跟进报价', value: 9, icon: '□' },
    { tone: 'lilac', label: '报价待转化', value: 5, icon: '⇄' },
    { tone: 'mint', label: '待审批合同', value: 6, icon: '✓' },
    { tone: 'sky', label: '合同待下单', value: 8, icon: '▦' },
    { tone: 'sky', label: '待确认订单', value: 18, icon: '▣' },
    { tone: 'peach', label: '待出库订单', value: 12, icon: '↑' },
    { tone: 'mint', label: '待开票申请', value: 7, icon: '□' },
    { tone: 'sky', label: '待回款核销', value: 11, icon: '¥' },
    { tone: 'rose', label: '逾期未回款', value: 2, icon: '!' },
    { tone: 'sand', label: '退换货待处理', value: 5, icon: '↩' },
  ],
  tiles: [
    { label: '客户', sub: '档案/联系人/财务/授信', count: 238, tint: '#DCE7FB', color: '#5677FC', icon: '◇' },
    { label: '计划', sub: '年度/月度计划/目标拆解', count: 12, tint: '#DBF3E6', color: '#10B981', icon: '▤' },
    { label: '报价', sub: '产品明细/阶梯价/转化', count: 46, tint: '#FEF3CD', color: '#B26A24', icon: '□' },
    { label: '合同', sub: '合同条款/收款/开票', count: 32, tint: '#E8DEFB', color: '#8957D8', icon: '✓' },
    { label: '订单', sub: '订单明细/信用/出库', count: 78, tint: '#DCE7FB', color: '#5677FC', icon: '▣' },
    { label: '发货应收', sub: '出库/签收/应收生成', count: 24, tint: '#DBF3E6', color: '#10B981', icon: '↑' },
    { label: '开票', sub: '开票申请/发票登记', count: 7, tint: '#DCE7FB', color: '#5677FC', icon: '□' },
    { label: '回款', sub: '收款登记/核销/逾期', count: 19, tint: '#FEF3CD', color: '#B26A24', icon: '¥' },
    { label: '退货', sub: '销售退货/退款/入库', count: 5, tint: '#FBDFDF', color: '#D14D4D', icon: '↩' },
    { label: '换货', sub: '换出/换入/差额处理', count: 2, tint: '#E8DEFB', color: '#8957D8', icon: '⇄' },
    { label: '报表', sub: '业绩/客户/回款分析', count: 6, tint: '#DBF3E6', color: '#10B981', icon: '⌕' },
  ],
  entries: [
    { label: '新增客户', tint: '#DCE7FB', color: '#5677FC', icon: '◇' },
    { label: '制定计划', tint: '#DBF3E6', color: '#10B981', icon: '▤' },
    { label: '新增报价', tint: '#FEF3CD', color: '#B26A24', icon: '□' },
    { label: '新增合同', tint: '#E8DEFB', color: '#8957D8', icon: '✓' },
    { label: '新增订单', tint: '#DCE7FB', color: '#5677FC', icon: '▣' },
    { label: '信用审核', tint: '#FBDFDF', color: '#D14D4D', icon: '!' },
    { label: '开票申请', tint: '#DCE7FB', color: '#5677FC', icon: '□' },
    { label: '回款核销', tint: '#FEF3CD', color: '#B26A24', icon: '¥' },
  ],
  notices: [
    { type: '重要', text: '客户授信、报价有效期和订单信用校验已纳入销售中心待办，请优先处理超额订单', time: '2小时前', tone: 'aw-feed-tag-rose' },
    { type: '审批', text: '6 份销售合同待会签，审批完成后可继续转销售订单和发货应收', time: '今天 09:20', tone: 'aw-feed-tag-peach' },
    { type: '制度', text: '新版客户信用额度、报价转化和合同回款核销规则已发布', time: '1天前', tone: 'aw-feed-tag-sky' },
    { type: '系统', text: '销售订单确认后将联动仓储出库、开票申请和应收回款进度', time: '3天前', tone: 'aw-feed-tag-mint' },
    { type: '提醒', text: '退货和换货单据需同步核对原订单、发货记录、退款或差额收款', time: '4天前', tone: 'aw-feed-tag-peach' },
  ],
  recent: [
    { title: 'SC-202605-031 海南星海销售合同会签', meta: '销售 · 合同管理 · 12分钟前' },
    { title: 'CUS-2026-001 海南星海智能制造有限公司', meta: '销售 · 客户管理 · 1小时前' },
    { title: 'SQ-202605-018 深圳荣某精密阶梯报价', meta: '销售 · 报价管理 · 今天 09:24' },
    { title: 'SO-202605-026 广州智造电子信用校验', meta: '销售 · 订单管理 · 昨天 17:08' },
    { title: 'RCV-202605-012 华东客户回款核销', meta: '销售 · 回款管理 · 昨天 15:30' },
  ],
  focusRows: [
    { code: 'SC-202605-031', customer: '海南星海智能制造有限公司', stage: '合同会签', owner: '老夏', amount: '288,000', status: '审核中' },
    { code: 'SQ-202605-018', customer: '深圳荣某精密科技有限公司', stage: '报价跟进', owner: '李文涛', amount: '59,600', status: '待跟进' },
    { code: 'SO-202605-026', customer: '广州智造电子', stage: '信用校验/待出库', owner: '陈思源', amount: '126,800', status: '待处理' },
  ],
};

export const purchaseWorkbench = {
  kpis: [
    { tone: 'mint', label: '待审核供应商', value: 3, icon: '◇' },
    { tone: 'peach', label: '临时供应商转正', value: 2, icon: '⇄' },
    { tone: 'sky', label: '待提交请购', value: 5, icon: '▤' },
    { tone: 'mint', label: '待审批请购', value: 16, icon: '✓' },
    { tone: 'sand', label: '待转询价明细', value: 7, icon: '□' },
    { tone: 'peach', label: '询价中', value: 8, icon: '⌕' },
    { tone: 'rose', label: '待定价报价', value: 4, icon: '¥' },
    { tone: 'sky', label: '待下达采购', value: 12, icon: '▦' },
    { tone: 'mint', label: '到货待入库', value: 7, icon: '↓' },
    { tone: 'rose', label: '三单差异待审', value: 3, icon: '!' },
    { tone: 'lilac', label: '暂估应付待确认', value: 5, icon: '¥' },
    { tone: 'sand', label: '待付款申请', value: 9, icon: '✓' },
    { tone: 'sky', label: '到票待认证', value: 5, icon: '□' },
  ],
  tiles: [
    { label: '供应商', sub: '档案/联系人/财务/供货产品', count: 126, tint: '#DCE7FB', color: '#5677FC', icon: '◇' },
    { label: '请购', sub: '请购单/明细/转询价/转采购', count: 48, tint: '#DBF3E6', color: '#10B981', icon: '▤' },
    { label: '询价', sub: '报价/定价/临时供应商', count: 21, tint: '#FEF3CD', color: '#B26A24', icon: '□' },
    { label: '采购', sub: '订单/到货/入库/付款', count: 64, tint: '#DCE7FB', color: '#5677FC', icon: '▦' },
    { label: '三单匹配', sub: '订单/入库/发票差异', count: 11, tint: '#E8DEFB', color: '#8957D8', icon: '✓' },
    { label: '应付暂估', sub: '暂估/扣款/可付款', count: 18, tint: '#FEF3CD', color: '#B26A24', icon: '¥' },
    { label: '退货', sub: '采购退货', count: 4, tint: '#FBDFDF', color: '#D14D4D', icon: '↩' },
    { label: '换货', sub: '采购换货', count: 2, tint: '#E8DEFB', color: '#8957D8', icon: '⇄' },
    { label: '报表', sub: '供应商对账/产品统计', count: 6, tint: '#DBF3E6', color: '#10B981', icon: '⌕' },
  ],
  entries: [
    { label: '新增供应商', tint: '#DCE7FB', color: '#5677FC', icon: '◇' },
    { label: '新增请购', tint: '#DBF3E6', color: '#10B981', icon: '▤' },
    { label: '新增询价', tint: '#FEF3CD', color: '#B26A24', icon: '□' },
    { label: '新增采购', tint: '#DCE7FB', color: '#5677FC', icon: '▦' },
    { label: '请购明细', tint: '#DBF3E6', color: '#10B981', icon: '▣' },
    { label: '供应商审核', tint: '#E8DEFB', color: '#8957D8', icon: '✓' },
    { label: '三单匹配', tint: '#FEF3CD', color: '#B26A24', icon: '≡' },
    { label: '付款申请', tint: '#DCE7FB', color: '#5677FC', icon: '¥' },
  ],
  notices: [
    { type: '重要', text: 'MRP 采购建议已生成，请先复核待询价物料再下达采购订单', time: '2小时前', tone: 'aw-feed-tag-rose' },
    { type: '审批', text: '3 家临时供应商待转正，需补齐联系人、财务账户和资质附件', time: '今天 09:20', tone: 'aw-feed-tag-peach' },
    { type: '制度', text: '新版供应商准入、询价定价和免询价规则已发布', time: '1天前', tone: 'aw-feed-tag-sky' },
    { type: '系统', text: '采购订单到货将与仓储入库、IQC 放行和应付暂估联动校验', time: '3天前', tone: 'aw-feed-tag-mint' },
    { type: '提醒', text: '三单匹配差异需在付款申请前完成确认，质检扣款会同步影响可付款金额', time: '4天前', tone: 'aw-feed-tag-peach' },
  ],
  recent: [
    { title: 'SUP-2025-003 东莞华美包装制品厂', meta: '采购 · 供应商管理 · 12分钟前' },
    { title: 'PR-2026-00232 20240请购购物料00232', meta: '采购 · 请购管理 · 20分钟前' },
    { title: 'DD-2024-003 精密轴承询价', meta: '采购 · 询价管理 · 1小时前' },
    { title: 'CG-20251221003 差异待审采购订单', meta: '采购 · 采购订单 · 昨天 17:08' },
    { title: 'AP-EST-20251223001 暂估应付确认', meta: '采购 · 应付暂估 · 昨天 15:30' },
  ],
};

export const rdWorkbench = {
  kpis: [
    { tone: 'peach', label: '待审批文档', value: 10, icon: '□' },
    { tone: 'mint', label: '待评审新品', value: 4, icon: '▤' },
    { tone: 'sky', label: '待发布产品', value: 3, icon: '▣' },
    { tone: 'rose', label: '待维护物料', value: 6, icon: '▦' },
    { tone: 'lilac', label: '待完善工序', value: 5, icon: '⇄' },
    { tone: 'sand', label: '待审核工艺', value: 3, icon: '✎' },
    { tone: 'sky', label: '待提交BOM', value: 4, icon: '▦' },
    { tone: 'mint', label: '待确认替代料', value: 2, icon: '⇄' },
    { tone: 'peach', label: '待处理版本变更', value: 3, icon: 'V' },
    { tone: 'rose', label: '待补充研发附件', value: 7, icon: 'A' },
  ],
  tiles: [
    { label: '文档库', sub: '研发文档', count: 25, tint: '#DCE7FB', color: '#5677FC', icon: '□' },
    { label: '新品', sub: '新品研发', count: 28, tint: '#DCE7FB', color: '#5677FC', icon: '▤' },
    { label: '产品', sub: '产品库', count: 18, tint: '#DCE7FB', color: '#5677FC', icon: '▣' },
    { label: '物料', sub: '物料管理', count: 52, tint: '#DCE7FB', color: '#5677FC', icon: '▦' },
    { label: '工序', sub: '工序管理', count: 16, tint: '#FEF3CD', color: '#B26A24', icon: '⇄' },
    { label: '工艺', sub: '工艺管理', count: 12, tint: '#FBDFDF', color: '#D14D4D', icon: '✎' },
    { label: 'BOM', sub: 'BOM管理', count: 24, tint: '#E8DEFB', color: '#8957D8', icon: '▦' },
    { label: '替代料', sub: '代替料库', count: 9, tint: '#DBF3E6', color: '#10B981', icon: '⇄' },
  ],
  entries: [
    { label: '新增文档', tint: '#DCE7FB', color: '#5677FC', icon: '□' },
    { label: '新增新品', tint: '#DCE7FB', color: '#5677FC', icon: '▤' },
    { label: '新增产品', tint: '#DCE7FB', color: '#5677FC', icon: '▣' },
    { label: '新增物料', tint: '#DCE7FB', color: '#5677FC', icon: '▦' },
    { label: '新增工序', tint: '#FEF3CD', color: '#B26A24', icon: '⇄' },
    { label: '新增工艺', tint: '#FBDFDF', color: '#D14D4D', icon: '✎' },
    { label: '新增BOM', tint: '#E8DEFB', color: '#8957D8', icon: 'B' },
    { label: '新增替代料', tint: '#DBF3E6', color: '#10B981', icon: '⇄' },
  ],
  notices: [
    { type: '重要', text: '智能输送线新品研发进入阶段评审，请补齐研发说明、物料清单和工艺流程', time: '2小时前', tone: 'aw-feed-tag-rose' },
    { type: '制度', text: '新版研发文档分类、编号、审批和外发水印策略已发布', time: '1天前', tone: 'aw-feed-tag-sky' },
    { type: '系统', text: 'BOM发布前需完成适用产品、版本、物料层级、替代料和工序关联校验', time: '3天前', tone: 'aw-feed-tag-mint' },
    { type: '提醒', text: '工序档案新增后请同步维护工时、技术参数、质检方案和关联文档', time: '4天前', tone: 'aw-feed-tag-peach' },
  ],
  recent: [
    { title: 'DOC-202605-018 智能温控锅装配规范', meta: '研发 · 文档库 · 12分钟前' },
    { title: 'XP-2025-001 智能输送线新品研发', meta: '研发 · 新品研发 · 1小时前' },
    { title: 'CP-20260521001 iPhone17', meta: '研发 · 产品库 · 今天 10:05' },
    { title: 'GY-202605-001 智能温控锅总装工艺', meta: '研发 · 工艺管理 · 今天 09:48' },
    { title: 'BOM-202605-001 智能温控锅生产BOM', meta: '研发 · BOM管理 · 今天 09:30' },
  ],
};

export const warehouseWorkbench = {
  kpis: [
    { tone: 'rose', label: '库存预警', value: 6, icon: '!' },
    { tone: 'mint', label: '待收货入库', value: 14, icon: '↓' },
    { tone: 'peach', label: '待上架过账', value: 7, icon: '▦' },
    { tone: 'sky', label: '待拣货出库', value: 22, icon: '↑' },
    { tone: 'lilac', label: 'OQC待放行', value: 5, icon: '□' },
    { tone: 'mint', label: 'IQC待检', value: 8, icon: '✓' },
    { tone: 'lilac', label: '待确认调拨', value: 5, icon: '⇄' },
    { tone: 'sand', label: '盘点差异待调', value: 3, icon: '≡' },
    { tone: 'sky', label: '冻结占用待释放', value: 9, icon: '▣' },
    { tone: 'peach', label: '库位容量预警', value: 4, icon: '□' },
  ],
  tiles: [
    { label: '库存', sub: '台账/批次/成本层/冻结占用', count: 892, tint: '#DCE7FB', color: '#5677FC', icon: '▦' },
    { label: '入库', sub: '采购/生产/退货/委外入库', count: 36, tint: '#DBF3E6', color: '#10B981', icon: '↓' },
    { label: '出库', sub: '销售/领用/委外/退货出库', count: 42, tint: '#FEF3CD', color: '#B26A24', icon: '↑' },
    { label: '调拨', sub: '冻结/调出/在途/调入差异', count: 12, tint: '#E8DEFB', color: '#8957D8', icon: '⇄' },
    { label: '盘点', sub: '整仓/库区/库位/SKU盘点', count: 7, tint: '#FBDFDF', color: '#D14D4D', icon: '≡' },
    { label: '库位', sub: '仓库/区域/库位/容量', count: 320, tint: '#DCE7FB', color: '#5677FC', icon: '□' },
    { label: '来料质检', sub: 'IQC抽样/让步/拒收', count: 8, tint: '#DBF3E6', color: '#10B981', icon: '✓' },
    { label: '出库质检', sub: 'OQC放行/客户验货/拦截', count: 5, tint: '#FEF3CD', color: '#B26A24', icon: '□' },
    { label: '追溯', sub: '物码/批次/出入库流水', count: 18, tint: '#E8DEFB', color: '#8957D8', icon: '⌕' },
  ],
  entries: [
    { label: '新增入库', tint: '#DBF3E6', color: '#10B981', icon: '↓' },
    { label: '新增出库', tint: '#FEF3CD', color: '#B26A24', icon: '↑' },
    { label: '新增调拨', tint: '#E8DEFB', color: '#8957D8', icon: '⇄' },
    { label: '创建盘点', tint: '#FBDFDF', color: '#D14D4D', icon: '≡' },
    { label: '库存调整', tint: '#DCE7FB', color: '#5677FC', icon: '▦' },
    { label: '新增仓库', tint: '#DCE7FB', color: '#5677FC', icon: '□' },
    { label: '新增库位', tint: '#DBF3E6', color: '#10B981', icon: '▣' },
    { label: '发起IQC', tint: '#DBF3E6', color: '#10B981', icon: '✓' },
    { label: '发起OQC', tint: '#FEF3CD', color: '#B26A24', icon: '□' },
  ],
  notices: [
    { type: '重要', text: '原料仓 A 区低库存和库位容量预警已触发，请先复核可用量、占用量和补货建议', time: '1小时前', tone: 'aw-feed-tag-rose' },
    { type: '质检', text: '采购到货入库需等待 IQC 判定后上架，销售出库需完成 OQC 放行后过账', time: '今天 09:35', tone: 'aw-feed-tag-peach' },
    { type: '系统', text: '出入库过账将同步更新库存台账、成本层、物码追溯和财务应收应付确认点', time: '1天前', tone: 'aw-feed-tag-mint' },
    { type: '提醒', text: '调拨单需按调拨冻结、调出确认、在途、调入确认和差异调整顺序处理', time: '2天前', tone: 'aw-feed-tag-sky' },
    { type: '公告', text: '本月循环盘点任务已生成，可按整仓、库区、库位或SKU选择盘点范围', time: '3天前', tone: 'aw-feed-tag-peach' },
  ],
  recent: [
    { title: 'IN-202605-031 采购到货入库', meta: '仓储 · 入库管理 · 16分钟前' },
    { title: 'OQC-202605-001 销售出库放行', meta: '仓储 · 出库质检 · 32分钟前' },
    { title: 'OUT-202605-027 销售出库拣货复核', meta: '仓储 · 出库管理 · 45分钟前' },
    { title: 'TR-202605-004 原料仓调拨差异确认', meta: '仓储 · 调拨管理 · 昨天 15:10' },
    { title: 'PD-202605-006 成品区循环盘点', meta: '仓储 · 盘点管理 · 昨天 09:40' },
  ],
};

export const productionWorkbench = {
  kpis: [
    { tone: 'mint', label: '待确认需求', value: 10, icon: '▤' },
    { tone: 'rose', label: '缺料待处理', value: 4, icon: '!' },
    { tone: 'peach', label: '待齐套计划', value: 6, icon: '≡' },
    { tone: 'sky', label: '待释放订单', value: 9, icon: '□' },
    { tone: 'rose', label: '待领料工序', value: 11, icon: '↓' },
    { tone: 'sky', label: '待派工工单', value: 18, icon: '✓' },
    { tone: 'lilac', label: '待报工记录', value: 24, icon: '✎' },
    { tone: 'mint', label: '待质检放行', value: 7, icon: '▣' },
    { tone: 'sand', label: '异常工序', value: 4, icon: '!' },
    { tone: 'mint', label: '完工待入库', value: 8, icon: '↑' },
    { tone: 'peach', label: '委外待收货', value: 5, icon: '↗' },
    { tone: 'lilac', label: '排班冲突', value: 3, icon: '⇄' },
  ],
  tiles: [
    { label: '需求', sub: '销售/备货/试制需求确认', count: 31, tint: '#DCE7FB', color: '#5677FC', icon: '▤' },
    { label: '计划', sub: 'MRP/齐套/排产/审批', count: 18, tint: '#DBF3E6', color: '#10B981', icon: '▦' },
    { label: '订单', sub: 'BOM锁版/工艺锁版/释放', count: 42, tint: '#DCE7FB', color: '#5677FC', icon: '□' },
    { label: '工单', sub: '领料/派工/报工/质检', count: 86, tint: '#FEF3CD', color: '#B26A24', icon: '✓' },
    { label: '排班', sub: '班组/班次/工作日历/冲突', count: 12, tint: '#E8DEFB', color: '#8957D8', icon: '▣' },
    { label: '委外', sub: '委外明细/发料/收货/入库', count: 9, tint: '#FBDFDF', color: '#D14D4D', icon: '↗' },
    { label: '报工', sub: '领工派工/任务报工/记录', count: 24, tint: '#DCE7FB', color: '#5677FC', icon: '✎' },
    { label: '入库', sub: '完工入库/委外入库联动', count: 8, tint: '#DBF3E6', color: '#10B981', icon: '↑' },
  ],
  entries: [
    { label: '新增需求', tint: '#DCE7FB', color: '#5677FC', icon: '▤' },
    { label: '新增计划', tint: '#DBF3E6', color: '#10B981', icon: '▦' },
    { label: '新增订单', tint: '#DCE7FB', color: '#5677FC', icon: '□' },
    { label: '新增工单', tint: '#FEF3CD', color: '#B26A24', icon: '✓' },
    { label: '领工派工', tint: '#FEF3CD', color: '#B26A24', icon: '⇄' },
    { label: '任务报工', tint: '#DCE7FB', color: '#5677FC', icon: '✎' },
    { label: '委外加工', tint: '#FBDFDF', color: '#D14D4D', icon: '↗' },
    { label: '新增排班', tint: '#E8DEFB', color: '#8957D8', icon: '▣' },
    { label: '齐套检查', tint: '#DBF3E6', color: '#10B981', icon: '≡' },
  ],
  notices: [
    { type: '重要', text: '本周重点生产订单齐套状态已更新，缺料计划需先处理 MRP 建议再释放工单', time: '2小时前', tone: 'aw-feed-tag-rose' },
    { type: '排产', text: '3 份排班计划存在工时冲突，请复核班组、班次和工作日历后再发布', time: '今天 09:30', tone: 'aw-feed-tag-peach' },
    { type: '系统', text: '生产领料、报工、IPQC/FQC质检和完工入库联动规则已启用', time: '1天前', tone: 'aw-feed-tag-mint' },
    { type: '提醒', text: '委外加工发料、收货、质检和入库需要按委外明细逐项回写状态', time: '2天前', tone: 'aw-feed-tag-sky' },
    { type: '公告', text: '生产订单确认后请先锁定 BOM 与工艺版本，再释放工单明细', time: '4天前', tone: 'aw-feed-tag-peach' },
  ],
  recent: [
    { title: 'MO-202605-017 高精度伺服电机 BOM/工艺锁版', meta: '生产 · 生产订单 · 12分钟前' },
    { title: 'WO-202605-088 装配工序派工与领料', meta: '生产 · 生产工单 · 50分钟前' },
    { title: 'PLAN-202605-006 华南排产计划齐套检查', meta: '生产 · 生产计划 · 昨天 10:25' },
    { title: 'OS-202605-004 委外加工待收货', meta: '生产 · 委外加工 · 昨天 09:40' },
    { title: 'SCH-202606-001 总装一班排班冲突', meta: '生产 · 生产排班 · 前天 16:05' },
  ],
};

export const qcWorkbench = {
  kpis: [
    { tone: 'sky', label: '待报检任务', value: 4, icon: '报' },
    { tone: 'mint', label: '抽样/检验中', value: 5, icon: '检' },
    { tone: 'peach', label: '待判定结果', value: 3, icon: '判' },
    { tone: 'rose', label: '不合格/NCR', value: 5, icon: '异' },
    { tone: 'sand', label: '隔离/拒收', value: 2, icon: '隔' },
    { tone: 'lilac', label: '待复检任务', value: 2, icon: '复' },
    { tone: 'peach', label: '让步审批', value: 1, icon: '让' },
    { tone: 'rose', label: 'CAPA/8D', value: 1, icon: '改' },
    { tone: 'mint', label: '已放行', value: 4, icon: '行' },
    { tone: 'sky', label: '待生成报告', value: 3, icon: '报' },
    { tone: 'peach', label: '待审批方案', value: 1, icon: '审' },
  ],
  tiles: [
    { label: '质检执行', sub: '新增、抽样、判定、回写', count: 6, tint: '#DCE7FB', color: '#5677FC', icon: 'QC' },
    { label: 'IQC来料', sub: '到货待检、供应商批次', count: 2, tint: '#DBF3E6', color: '#10B981', icon: 'IQC' },
    { label: 'IPQC过程', sub: '首检、巡检、返工复检', count: 2, tint: '#E8DEFB', color: '#8957D8', icon: 'IP' },
    { label: 'FQC成品', sub: '完工入库前检验', count: 1, tint: '#DCE7FB', color: '#5677FC', icon: 'FQ' },
    { label: 'OQC出货', sub: '出库放行、客户验货', count: 1, tint: '#FEF3CD', color: '#B26A24', icon: 'OQ' },
    { label: '异常NCR', sub: '不合格、隔离、拒收', count: 5, tint: '#FBDFDF', color: '#D14D4D', icon: 'NCR' },
    { label: 'MRB/让步', sub: '会审、特采、业务确认', count: 2, tint: '#FFF1F0', color: '#CF1322', icon: 'MRB' },
    { label: '复检关闭', sub: '返工复检、验证关闭', count: 3, tint: '#F6FFED', color: '#389E0D', icon: 'RCK' },
    { label: '方案标准', sub: '质检方案、质检组、标准', count: 9, tint: '#F3EDFF', color: '#722ED1', icon: 'STD' },
    { label: '质检分析', sub: '趋势、不良、供应商、工序', count: 4, tint: '#E6FFFB', color: '#08979C', icon: 'ANA' },
  ],
  entries: [
    { label: '新增检验任务', tint: '#DCE7FB', color: '#5677FC', icon: '+' },
    { label: '执行质检', tint: '#DBF3E6', color: '#10B981', icon: '检' },
    { label: '待检任务', tint: '#FEF3CD', color: '#B26A24', icon: '待' },
    { label: '不合格记录', tint: '#FBDFDF', color: '#D14D4D', icon: '异' },
    { label: '隔离/拒收', tint: '#FFF1F0', color: '#CF1322', icon: '隔' },
    { label: 'MRB评审', tint: '#F3EDFF', color: '#722ED1', icon: '审' },
    { label: '返工复检', tint: '#E8DEFB', color: '#8957D8', icon: '复' },
    { label: '让步放行', tint: '#FEF3CD', color: '#B26A24', icon: '让' },
    { label: '验证关闭', tint: '#F6FFED', color: '#389E0D', icon: '关' },
    { label: '检验方案', tint: '#DCE7FB', color: '#5677FC', icon: '方' },
    { label: '质量趋势', tint: '#E6FFFB', color: '#08979C', icon: '析' },
  ],
  notices: [
    { type: 'IQC', text: '采购到货批次已同步到质检中心，请完成抽样和判定后再回写仓储上架数量', time: '30分钟前', tone: 'aw-feed-tag-rose' },
    { type: 'IPQC', text: '生产报工待质检、返工复检和工序放行已纳入质检执行链路', time: '2小时前', tone: 'aw-feed-tag-mint' },
    { type: '异常', text: '不合格判定会生成 NCR，可继续走隔离/拒收、MRB、复检、让步和验证关闭', time: '今天 09:20', tone: 'aw-feed-tag-peach' },
    { type: '标准', text: '质检方案由质检组和质检标准组成，停用后不影响历史质检追溯', time: '昨天 17:30', tone: 'aw-feed-tag-sky' },
  ],
  recent: [
    { title: 'IQC-202605-001 采购到货质检', meta: '质检 · 来料检验 IQC · 12分钟前' },
    { title: 'NCR-202605-001 尺寸偏差不合格处置', meta: '质检 · 异常处理 · 35分钟前' },
    { title: 'IPQC-202605-001 三工序巡检', meta: '质检 · 过程检验 IPQC · 1小时前' },
    { title: 'PLAN-202605-001 轴承来料检验方案', meta: '质检 · 检验方案 · 昨天 16:40' },
    { title: 'QCR-202605-001 近30天质量趋势', meta: '质检 · 质量趋势 · 昨天 10:15' },
  ],
};

export const workbenchByCenter = {
  rd: rdWorkbench,
  sales: salesWorkbench,
  purchase: purchaseWorkbench,
  warehouse: warehouseWorkbench,
  production: productionWorkbench,
  qc: qcWorkbench,
};
