import type { RdResourceConfig } from './types';

export const rdResourceConfigs: Record<string, RdResourceConfig> = {
  projects: {
    key: 'projects',
    title: '研发项目',
    createLabel: '新增研发项目',
    searchPlaceholder: '搜索项目名称、编号、客户、产品、负责人',
    primaryKey: 'name',
    statusKey: 'statusName',
    columns: [
      { key: 'code', title: '项目编号', width: 150 },
      { key: 'name', title: '项目名称', width: 220, link: true },
      { key: 'customerName', title: '客户', width: 180 },
      { key: 'productName', title: '目标产品', width: 160 },
      { key: 'ownerName', title: '项目负责人', width: 110 },
      { key: 'startDate', title: '立项日期', width: 120 },
      { key: 'expectedDate', title: '计划完成', width: 120 },
      { key: 'bomStatusName', title: 'BOM状态', width: 110, status: true },
      { key: 'processStatusName', title: '工艺状态', width: 110, status: true },
      { key: 'quoteStatusName', title: '报价状态', width: 110, status: true },
      { key: 'statusName', title: '项目状态', width: 110, status: true },
    ],
    formFields: [
      { key: 'name', label: '项目名称', required: true },
      { key: 'customerName', label: '客户', required: true },
      { key: 'productName', label: '目标产品', required: true },
      { key: 'ownerName', label: '项目负责人' },
      { key: 'startDate', label: '立项日期', type: 'date' },
      { key: 'expectedDate', label: '计划完成日期', type: 'date' },
      { key: 'priorityName', label: '优先级', type: 'select', options: ['高', '中', '低'] },
      { key: 'description', label: '项目说明', type: 'textarea' },
    ],
  },
  boms: {
    key: 'boms',
    title: 'BOM管理',
    createLabel: '新增BOM',
    searchPlaceholder: '搜索BOM名称、编号、适用产品、版本、编制人',
    primaryKey: 'name',
    statusKey: 'statusName',
    columns: [
      { key: 'code', title: 'BOM编号', width: 150 },
      { key: 'name', title: 'BOM名称', width: 220, link: true },
      { key: 'productName', title: '适用产品', width: 180 },
      { key: 'version', title: '版本', width: 90 },
      { key: 'typeName', title: 'BOM类型', width: 120 },
      { key: 'materialCount', title: '物料数', width: 90, numeric: true },
      { key: 'totalCost', title: '成本估算', width: 120, numeric: true },
      { key: 'authorName', title: '编制人', width: 110 },
      { key: 'effectiveDate', title: '生效日期', width: 120 },
      { key: 'statusName', title: '状态', width: 110, status: true },
    ],
    formFields: [
      { key: 'name', label: 'BOM名称', required: true },
      { key: 'productName', label: '适用产品', required: true },
      { key: 'version', label: '版本号' },
      { key: 'typeName', label: 'BOM类型', type: 'select', options: ['设计BOM', '制造BOM', '项目BOM'] },
      { key: 'authorName', label: '编制人' },
      { key: 'effectiveDate', label: '生效日期', type: 'date' },
    ],
  },
  processes: {
    key: 'processes',
    title: '工艺路线',
    createLabel: '新增工艺路线',
    searchPlaceholder: '搜索工艺名称、编号、适用产品、版本、编制人',
    primaryKey: 'name',
    statusKey: 'statusName',
    columns: [
      { key: 'code', title: '工艺编号', width: 150 },
      { key: 'name', title: '工艺名称', width: 220, link: true },
      { key: 'productName', title: '适用产品', width: 180 },
      { key: 'version', title: '版本', width: 90 },
      { key: 'categoryName', title: '工艺分类', width: 120 },
      { key: 'operationCount', title: '工序数', width: 90, numeric: true },
      { key: 'outsourcingCount', title: '委外工序', width: 100, numeric: true },
      { key: 'standardHours', title: '标准工时', width: 110, numeric: true },
      { key: 'authorName', title: '编制人', width: 110 },
      { key: 'statusName', title: '状态', width: 110, status: true },
    ],
    formFields: [
      { key: 'name', label: '工艺名称', required: true },
      { key: 'productName', label: '适用产品', required: true },
      { key: 'version', label: '版本号' },
      { key: 'categoryName', label: '工艺分类', type: 'select', options: ['装配工艺', '电子工艺', '测试工艺', '包装工艺'] },
      { key: 'authorName', label: '编制人' },
      { key: 'effectiveDate', label: '生效日期', type: 'date' },
    ],
  },
};
